[packages.universal.cloud]
aws-cli = { manager = "mise", test = "aws --version" }
azure-cli = { test = "az --version" }

[packages.universal.common]
act = { test = "act --version" }
age-plugin-yubikey = { test = "age-plugin-yubikey --version" }
bash = { test = "bash --version" }
bat = { test = "bat --version" }
broot = { test = "broot --version" }
btop = { disabled = "ephemeral", test = "btop --version" }
chezmoi = { test = "chezmoi --version" }
coreutils = { test = "realpath --version" }
croc = { test = "croc --version" }
curl = { test = "curl --version" }
direnv = { test = "direnv version" }
duf = { test = "duf --version" }
dust = { test = "dust --version" }
eza = { test = "eza --version" }
fd = { test = "fd --version" }
fzf = { test = "fzf --version" }
gh = { test = "gh --version" }
git = { test = "git --version" }
git-delta = { test = "delta --version" }
gnupg = { test = "gpg --version" }
httpie = { test = "http --version" }
hyperfine = { test = "hyperfine --version" }
jq = { test = "jq --version" }
mise = { test = "mise --version" }
mkcert = { test = "mkcert -version" }
neovim = { manager = "mise", test = "nvim --version", version = "0.11.4" }
procs = { test = "procs --version" }
rage = { test = "rage --version" }
rclone = { test = "rclone --version" }
ripgrep = { test = "rg --version" }
sd = { test = "sd --version" }
tmux = { test = "tmux -V" }
tokei = { test = "tokei --version" }
vivid = { test = "vivid --version" }
wget = { test = "wget --version" }
zsh = { test = "zsh --version" }
jj = { manager = "mise", test = "jj --version" }
lazygit = { manager = "mise", test = "lazygit --version" }
mpv = { disabled = "headless", manager = "system", test = "mpv --version" }
zk = { manager = "mise", name = "github:zk-org/zk", test = "zk --version" }

# LSPs
typos = { manager = "mise", name = "cargo:crate-ci/typos" }
typos-lsp = { manager = "mise", name = "cargo:tekumara/typos-lsp" }
bash-language-server = { manager = "mise", name = "npm:bash-language-server" }
tree-sitter = { manager = "mise", name = "github:tree-sitter/tree-sitter" }
mutt-ls = { manager = "mise", name = "pipx:mutt-language-server" }
taplo = { manager = "mise", test = "taplo --version" }
yamlls = { manager = "mise", name = "npm:yaml-language-server" }
hado = { manager = "mise", name = "github:hadolint/hadolint" }

# Formatters
prettier = { manager = "mise", test = "prettier --version" }
stylua = { manager = "mise", test = "stylua --version" }
shfmt = { manager = "mise", name = "github:mvdan/sh", test = "shfmt --version" }
clang-format = { manager = "mise", name = "pipx:clang-format", test = "clang-format --version" }


[packages.universal.docker]
docker = { test = "docker -v" }
docker-compose = { test = "docker compose version" }
docker-buildx = { test = "docker buildx version" }
dive = { manager = "mise", name = "ubi:wagoodman/dive", test = "dive --version" }
dockerfile-ls = { manager = "mise", name = "npm:dockerfile-language-server-nodejs", version = "latest" }
docker-compose-ls = { manager = "mise", name = "npm:@microsoft/compose-language-service", version = "latest" }

[packages.universal.extra]
gocryptfs = { disabled = "headless,restricted", test = "gocryptfs -version" }
qrencode = { test = "qrencode --version" }
unison = { test = "unison -version" }
zbar = { test = "zbarimg --version" }
claude-code = { manager = "mise", test = "claude --version" }
opencode = { manager = "mise", test = "opencode --version" }
repomix = { manager = "mise", name = "npm:repomix", test = "repomix --version" }

[packages.universal.golang]
go = { manager = "mise", test = "go version" }
goimports = { manager = "mise", test = "goimports version", name = "go:golang.org/x/tools/cmd/goimports" }
gopls = { manager = "mise", name = "go:golang.org/x/tools/gopls", test = "gopls version" }

[packages.universal.iac]
terraform = { manager = "mise", test = "terraform version" }
terragrunt = { manager = "mise", test = "terragrunt --version" }
sops = { manager = "mise", test = "sops --version" }
tflint = { manager = "mise", test = "tflint --version" }
shellcheck = { manager = "mise", test = "shellcheck --version" }

[packages.universal.java]
ant = { manager = "mise", test = "ant -version" }
maven = { manager = "mise", test = "mvn -v" }
java = { manager = "mise", test = "java -version", version = "temurin-21.0.8+9.0.LTS" }
"http:jdtls" = { manager = "mise", version = "1.56.0", test = "jdtls --version", url = "https://download.eclipse.org/jdtls/milestones/{{ version }}/jdt-language-server-{{ version }}-202601291528.tar.gz" }
"http:lombok" = { manager = "mise", url = "https://projectlombok.org/downloads/lombok.jar" }


[packages.universal.kubernetes]
datree = { manager = "mise", test = "datree version" }
helm = { manager = "mise", test = "helm version" }
k3d = { manager = "mise", test = "k3d version" }
k9s = { manager = "mise", test = "k9s version" }
kubectl = { manager = "mise", test = "kubectl version --client" }
kubectx = { manager = "mise", test = "kubectx --help" }
kubens = { manager = "mise", test = "kubens --help" }
kubecolor = { manager = "mise", test = "kubecolor help" }
kubesess = { manager = "mise", name = "ubi:Ramilito/kubesess", test = "kubesess --help" }
kustomize = { manager = "mise", test = "kustomize version" }
oc = { manager = "mise", test = "oc version --client" }
popeye = { manager = "mise", test = "popeye version" }
stern = { manager = "mise", test = "stern --version" }
yq = { manager = "mise", test = "yq --version" }
kubectl-access-matrix = { manager = "krew", name = "access-matrix", test = "kubectl access-matrix --help" }
kubectl-blame = { manager = "krew", name = "blame", test = "kubectl blame --help" }
kubectl-cost = { manager = "krew", name = "cost", test = "kubectl cost --help" }
kubectl-datree = { manager = "krew", name = "datree", test = "kubectl datree version" }
kubectl-deprecations = { manager = "krew", name = "deprecations", test = "kubectl deprecations --help" }
kubectl-get-all = { manager = "krew", name = "get-all", test = "kubectl get-all --help" }
kubectl-images = { manager = "krew", name = "images", test = "kubectl images --help" }
kubectl-konfig = { manager = "krew", name = "konfig", test = "kubectl konfig --help" }
kubectl-kubescape = { manager = "krew", name = "kubescape", test = "kubectl kubescape --help" }
kubectl-kyverno = { manager = "krew", name = "kyverno", test = "kubectl kyverno --help" }
kubectl-modify-secret = { manager = "krew", name = "modify-secret", test = "kubectl modify-secret --help" }
kubectl-neat = { manager = "krew", name = "neat", test = "kubectl neat --help" }
kubectl-node-shell = { manager = "krew", name = "node-shell", test = "kubectl node-shell --version" }
kubectl-outdated = { manager = "krew", name = "outdated", test = "kubectl outdated --help" }
kubectl-rbac-tool = { manager = "krew", name = "rbac-tool", test = "kubectl rbac-tool --help" }
kubectl-resource-capacity = { manager = "krew", name = "resource-capacity", test = "kubectl resource-capacity --help" }
kubectl-score = { manager = "krew", name = "score", test = "kubectl score --help" }
kubectl-slice = { manager = "krew", name = "slice", test = "kubectl slice --help" }
kubectl-sniff = { manager = "krew", name = "sniff", test = "kubectl sniff --help" }
kubectl-tree = { manager = "krew", name = "tree", test = "kubectl tree --help" }
kubectl-tunnel = { manager = "krew", name = "tunnel", test = "kubectl tunnel --help" }
kubectl-view-allocations = { manager = "krew", name = "view-allocations", test = "kubectl view-allocations --help" }
kubectl-who-can = { manager = "krew", name = "who-can", test = "kubectl who-can --help" }
helm-diff = { manager = "helm", name = "https://github.com/databus23/helm-diff", test = "helm diff --help" }

[packages.universal.node]
node = { manager = "mise", test = "node --version && npm --version && yarn --version && pnpm --version", version = "22" }

[packages.universal.python]
python = { manager = "mise", test = "python3 --version && pip --version && pre-commit --version" }
uv = { manager = "mise", name = "uv", test = "uv --version" }
ruff = { manager = "mise", test = "ruff --version" }
basedpyright = { manager = "mise", name = "pipx:DetachHead/basedpyright" }

[packages.universal.rust]
rust = { manager = "mise", test = "rustc --version" }
rust-analyzer = { manager = "mise", name = "github:rust-lang/rust-analyzer", test = "rust-analyzer --version" }

[packages.universal.cpp]
clangd = { manager = "mise", name = "github:clangd/clangd@21.1.8" }

[packages.universal.web]
tailwindcss = { manager = "mise", name = "npm:tailwindcss-language-server" }
deno = { manager = "mise", version = "latest", test = "deno --version" }
vtsls = { manager = "mise", version = "latest", name = "npm:vtsls", test = "vstls --version" }
tsgo = { manager = "mise", version = "latest", name = "npm:tsgo", test = "tsgo --version" }
oxlint = { manager = "mise", version = "latest", name = "npm:oxlint", test = "oxlint --version" }
oxfmt = { manager = "mise", version = "latest", name = "npm:oxfmt", test = "oxfmt --version" }
stylelint_lsp = { manager = "mise", version = "latest", name = "npm:stylelint-lsp", test = "oxfmt --version" }
vscode-langservers-extracted = { manager = "mise", version = "latest", name = "npm:vscode-langservers-extracted" }
biome = { manager = "mise", version = "latest" }

[packages.universal.lua]
emmylua-ls = { manager = "mise", name = "github:CppCXY/emmylua-analyzer-rust" }
