[colors]
ansi = [
  '#CCCCCC',
  '#333333',
  '#9A9A9A',
  '#868686',
  '#727272',
  '#AEAEAE',
  '#4A4A4A',
  '#5E5E5E',
]
background = '#cccccc'
brights = [
  '#5E5E5E',
  '#333333',
  '#9A9A9A',
  '#868686',
  '#727272',
  '#AEAEAE',
  '#4A4A4A',
  '#7C7C7C',
]

compose_cursor = '#bf5c5c'
cursor_bg = '#bf6a6a'
cursor_border = '#bf6a6a'
cursor_fg = '#474747'
foreground = '#474747'
scrollbar_thumb = '#A4A4A4'
selection_bg = '#A4A4A4'
selection_fg = '#333333'
split = '#B8B8B8'
visual_bell = '#B8B8B8'

[colors.indexed]
16 = '#727272'
17 = '#5E5E5E'

[colors.tab_bar]
background = '#b8b8b8'
inactive_tab_edge = '#474747'

[colors.tab_bar.active_tab]
bg_color = '#AEAEAE'
fg_color = '#333333'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c2c2c2'
fg_color = '#545454'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#cccccc'
fg_color = '#545454'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#C2C2C2'
fg_color = '#545454'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#CCCCCC'
fg_color = '#545454'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'


