# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "uas"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/243624a9-58b5-4e95-ba5c-e36cec4092f4";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/243624a9-58b5-4e95-ba5c-e36cec4092f4";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/243624a9-58b5-4e95-ba5c-e36cec4092f4";
    fsType = "btrfs";
    options = ["subvol=@data"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/96F0-EA3C";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
