return {
  "catppuccin",
  optional = true,
  opts = {
    flavour = "latte",
    background = { light = "latte", dark = "mocha" },
    color_overrides = {
      latte = {
        -- Darkened Catpuccin latte colors to help constrast with the base and mantle
        rosewater = "#bf6a6a",
        flamingo = "#bf5c5c",
        pink = "#c946a6",
        mauve = "#7a2fd9",
        red = "#b50d31",
        maroon = "#c2303d",
        peach = "#d65d0e",
        yellow = "#ad6c16",
        green = "#358524",
        teal = "#127378",
        sky = "#037ca1",
        sapphire = "#187c8d",
        blue = "#1850bf",
        lavender = "#5a68d6",
        text = "#24273a",
        subtext1 = "#363a4f",
        subtext0 = "#494d64",
        overlay2 = "#5b6078",
        overlay1 = "#6e738d",
        overlay0 = "#8087a2",
        surface2 = "#9399b2",
        surface1 = "#a5adcb",
        surface0 = "#b8c0e0",
        base = "#cccccc",
        mantle = "#c2c2c2",
        crust = "#b8b8b8",
      }
    },
    integrations = {
      blink_cmp = true,
      dap = {
        enabled = true,
        enable_ui = true,
      },
      gitsigns = true,
      lsp_trouble = true,
      mason = true,
      neotest = true,
      native_lsp = {
        enabled = true,
        virtual_text = {
          errors = { "italic" },
          hints = {},
          warnings = { "italic" },
          information = {},
        },
        underlines = {
          errors = { "undercurl" },
          hints = {},
          warnings = { "undercurl" },
          information = {},
        },
      },
      overseer = true,
      telescope = true,
      treesitter = true,
    },
    term_colors = false,
    styles = {
      comments = {},
      keywords = { "italic" },
    },
    compile = {
      enabled = true,
      path = vim.fn.stdpath("cache") .. "/catppuccin",
    },
    dim_inactive = {
      enabled = true,
      shade = "dark",
      percentage = 0.15,
    },
    custom_highlights = function(c)
      local bg_alt = "#A8A8A8"
      local bg = "#B8B8B8"
      return {
        BlinkCmpDocBorder = { fg = c.blue },
        BlinkCmpKind = { fg = c.blue },
        BlinkCmpMenu = { fg = c.text },
        BlinkCmpMenuBorder = { fg = c.blue },
        BlinkCmpSignatureHelpActiveParameter = { fg = c.mauve },
        BlinkCmpSignatureHelpBorder = { fg = c.blue },
        ColorColumn = { bg = c.mantle },
        Cursor = { fg = c.base, bg = "#d9e0ee" },
        Folded = { fg = c.lavender, bg = c.dim },
        MarkviewPalette1Fg = { fg = "#d9e0ee" },
        MarkviewCode = { bg = c.mantle },
        MarkviewCodeFg = { fg = c.mantle },
        MarkviewCodeInfo = { fg = c.overlay2, bg = c.mantle },
        TSConstBuiltin = { fg = c.maroon },
        TelescopeBorder = { fg = bg_alt, bg = bg },
        TelescopeNormal = { bg = bg },
        TelescopePreviewBorder = { fg = bg, bg = bg },
        TelescopePreviewNormal = { bg = bg },
        TelescopePreviewTitle = { fg = bg, bg = c.green },
        TelescopePromptBorder = { fg = bg_alt, bg = bg_alt },
        TelescopePromptNormal = { fg = c.text, bg = bg_alt },
        TelescopePromptPrefix = { fg = c.red, bg = bg_alt },
        TelescopePromptTitle = { fg = bg, bg = c.red },
        TelescopeResultsBorder = { fg = bg, bg = bg },
        TelescopeResultsNormal = { bg = bg },
        TelescopeResultsTitle = { fg = bg, bg = bg },
        TelescopeSelection = { bg = bg_alt },
        TermCursor = { fg = "#000000", bg = "#B7BDF8" },
        TreesitterContextLineNumber = { fg = "#494D64", bg = "#1e2030" },
        Unvisited = { bg = "#34344F" },
        ["@constant.builtin"] = { fg = c.maroon },
        rainbow1 = { fg = c.red, bg = "#302D41" },
        rainbow2 = { fg = c.peach, bg = "#302D41" },
        rainbow3 = { fg = c.yellow, bg = "#302D41" },
        rainbow4 = { fg = c.green, bg = "#302D41" },
        rainbow5 = { fg = c.sapphire, bg = "#302D41" },
        rainbow6 = { fg = c.lavender, bg = "#302D41" },
      }
    end,
  },
}
