name: Security Scan

on:
  schedule:
  - cron: 0 1 * * 6
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  security-scan:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808 # 0.33.0
      env:
        TRIVY_USERNAME: ${{ github.repository_owner }}
        TRIVY_PASSWORD: ${{ github.token }}
      with:
        image-ref: ghcr.io/${{ github.repository }}:latest
        ignore-unfixed: true
        vuln-type: os
        severity: CRITICAL,HIGH
        format: sarif
        output: trivy-results.sarif
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3
      with:
        sarif_file: trivy-results.sarif
